# Generated by Django 5.0.6 on 2024-07-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menue.parentcategory'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='branche',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Menue.branche'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parent_category_images/'),
        ),
    ]
